---
title: "Example data figures"
output: html_notebook
---

This code produces Figures 1,2, and 3 in "Estimating regression errors without ground truth values" by
Henri Tiittanen, Emilia Oikarinen, Andreas Henelius, and Kai Puolamäki


```{r}
library(e1071)
set.seed(42)
f <- function(x) { 1-(x-1)^2 }

data_tr <- data.frame(i=1:15,
                      x=sort(runif(15)),
                      y=NA)
data_tr$x <- data_tr$x+rnorm(15,sd=0.1)
data_tr$y <- f(data_tr$x)+rnorm(15,sd=0.05)

data_te1 <- data.frame(i=LETTERS[4:6],x=c(0.45,0.5,0.59),y=NA)
data_te1$y <- f(data_te1$x)+rnorm(3,sd=0.05)

data_te2 <- data.frame(i=LETTERS[1:3],x=c(1.65,1.7,1.79),y=NA)
data_te2$y <- f(data_te2$x)+rnorm(3,sd=0.05)


```

```{r}
seg <- data.frame(a=seq(from=1,by=3,length.out=4),b=NA)
seg[,"b"] <- seg[,"a"]+5
makef <- function(model=lm,data=data_tr) {
  m <- model(y~x,data=data)
  function(newdata) {
    predict(m,data.frame(x=newdata))
  }
}
f_full <- makef(svm)
f_seg <- vector("list",dim(seg)[1])
for(i in 1:dim(seg)[1]) {
  f_seg[[i]] <- makef(lm,data_tr[seg[i,"a"]:seg[i,"b"],])
}
```

```{r}
col4 <- c('#e41a1c','#377eb8','#4daf4a','#984ea3')
lty4 <- rep("dashed",4)
pch4 <- c(0,1,2,6)
xrange <- range(data_tr[,2],data_te1[,2],data_te2[,2])
xx <- seq(from=xrange[1]-0.05,to=xrange[2]+0.05,length.out=256)
for(onlydata in c(FALSE,TRUE)) {
pdf(if(onlydata) "figures/2dplotbare.pdf" else "figures/2dplot.pdf",width=7,height=7)
plot(c(0,2.4),c(0.2,1.25),type="n",bty="n",xlab="x",ylab="y")
rug(data_tr[,"x"],col="darkred")
rug(data_te2[,"x"])
lines(xx,f(xx),col="gray",lty="dotted",lwd=2)

if(!onlydata) {
lines(xx,f_full(xx),col="black",lwd=2)
for(i in 1:length(f_seg)) {
  lines(xx,f_seg[[i]](xx),col=col4[i],lty=lty4[i],lwd=2)
}
  text(xrange[2],0.9,labels="d (Alg. 2)",pos=4)
  text(xrange[2],0.6,labels="generalisation error",pos=4)
  for(i in 1:3) {
  arrows(x0=data_te2[i,"x"],
         y1=data_te2[i,"y"]+0.025,
         y0=f_full(data_te2[i,"x"]),lwd=1,
  col="black",
  length=0.1)
   arrows(x0=data_te2[i,"x"],
         y1=f_seg[[4]](data_te2[i,"x"]),
         y0=f_full(data_te2[i,"x"]),lwd=2,
  col="black",
  length=0.1) 
  }
  legend("topleft",legend=c("SVM model for (1,15)",
                          "segment model for (1,6)",
                          "segment model for (4,9)",
                          "segment model for (7,12)",
                          "segment model for (10,15)",
                          "process that generated data"),
       col=c("black",col4,"gray"),
       lty=c("solid",lty4,"dotted"),
       lwd=c(2,2,2,2,2,2),
       pch=c(NA,NA,NA,NA,NA,NA), #pch=c(NA,pch4,NA),
       cex=0.7)
}
  
text(data_tr[,2:3],labels=data_tr[,1],cex=1, col="darkred")
text(data_te2[,2:3],labels=data_te2[,1],cex=1)

dev.off()
}
```

```{r}
pdf("figures/1dplot.pdf",width=9,height=7)
plot(c(1,18.5),c(-0.2,2.3),type="n",xaxt="n",xlab="i",ylab="",bty="n")
abline(v=15.5,col="black",lty="dashed")
abline(v=18.5,col="black",lty="dashed")
text(15.5,1.65,labels="training",pos=2)
text(15.5,1.65,labels="testing",pos=4)
points(data_tr[,c("i","y")],col="black",pch=15)
points(data.frame(i=16:18,x=data_te2[,"y"]),col="black",pch=15)
text(x=1:18,rep(-0.25,18),labels=c(data_tr[,"i"],as.character(data_te2[,"i"])),
     col=c(rep("darkred",15),rep("black",3)))
legend("topleft",legend=c(
                          "y",
                          "estimate of y: SVM model for (1,15)",
                          "estimate of y: segment model for (1,6)",
                          "estimate of y: segment model for (4,9)",
                          "estimate of y: segment model for (7,12)",
                          "estimate of y: segment model for (10,15)"),
       col=c("black","black",col4),lty=c(NA,rep("solid",5)),pch=c(15,NA,pch4),lwd=c(1,2,1,1,1,1),
       cex=0.9)
text(x=(1+15)/2,y=-0.14,pos=3,col="black",cex=0.7,labels="SVM model for (1,15)")
lines(c(1,15),c(-0.14,-0.14),col="black",lwd=2)
for(i in 1:dim(seg)[1]) {
  points(1:15,f_seg[[i]](data_tr[1:15,"x"]),col=col4[i],pch=pch4[i])
  lines(1:15,f_seg[[i]](data_tr[1:15,"x"]),col=col4[i])
  text(x=(seg[i,"a"]+seg[i,"b"])/2,y=(i-1)*0.14,pos=3,col=col4[i],cex=0.7,
       labels=sprintf("segment model for (%d,%d)",seg[i,"a"],seg[i,"b"]))
  lines(c(seg[i,"a"],seg[i,"b"]),rep((i-1)*0.14,2),col=col4[i])
  points((seg[i,"a"]+seg[i,"b"])/2,(i-1)*0.14,col=col4[i],pch=pch4[i])
  points(16:18,f_seg[[i]](data_te2[,"x"]),col=col4[i],pch=pch4[i])
  lines(16:18,f_seg[[i]](data_te2[,"x"]),col=col4[i])
}
lines(1:15,f_full(data_tr[,"x"]),col="black",lwd=2)
lines(16:18,f_full(data_te2[,"x"]),col="black",lwd=2)
dev.off()
```


